sudo: false

language: node_js

node_js:
  - node

install:
  - npm ci

script:
  - npm run test -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$repo_token npm run coveralls

notifications:
  email: false
